# CMRxRecon2024 range-extraction engine.
#
# The dataset ships as two ZIP archives — the training `ChallengeData.zip` and the
# after-competition `ChallengeData_AfterCompetition.zip` — each split into raw 4 GiB
# fragments hosted as separate Synapse file entities. Both are handled identically. To
# pull one `.mat` file we:
#   1. look up its byte coordinates in the offset map (catalog/cmrxrecon2024_catalog.jl),
#   2. resolve a pre-signed S3 URL for each fragment it spans (Synapse REST API),
#   3. issue HTTP Range requests against S3 (no Synapse auth on the S3 leg),
#   4. concatenate, strip the ZIP local file header, and inflate the Deflate payload.
#
# Which archive a file belongs to is recorded in its `extra["archive"]` tag
# ("training" / "aftercompetition"); the tag selects the fragment entity-ID map and the
# fragment-name prefix. Both maps are generated by scripts/list_cmrxrecon2024_parts.jl.
#
# Access needs a Synapse Personal Access Token (see set_synapse_token!). Outbound
# HTTPS is required, so this path cannot run on networks where port 443 is blocked.

const _SYNAPSE_REPO = "https://repo-prod.prod.sagebase.org/repo/v1"
const _DEFAULT_CHUNK_BYTES = 4 * 1024^3   # 4 GiB; overridden by the parts TOML if present

# Per-archive configuration: where the fragment entity-ID map lives and how its fragment
# files are named. Both archives are otherwise fetched by identical code.
struct _ArchiveSpec
    parts_path::String     # path to the committed parts TOML
    name_prefix::String    # fragment file-name prefix, e.g. "ChallengeData.zip-part-"
    pad::Int               # zero-padding width of the numeric fragment suffix
end

const _ARCHIVES = Dict{String, _ArchiveSpec}(
    "training" => _ArchiveSpec(
        normpath(joinpath(@__DIR__, "..", "..", "data", "cmrxrecon2024_parts.toml")),
        "ChallengeData.zip-part-", 3,
    ),
    "aftercompetition" => _ArchiveSpec(
        normpath(joinpath(@__DIR__, "..", "..", "data", "cmrxrecon2024_aftercompetition_parts.toml")),
        "ChallengeData_AfterCompetition.zip-part-", 2,
    ),
)

# Memoised (parts map, chunk size) per archive tag, populated on first download.
const _CMRXRECON_PARTS = Dict{String, Tuple{Dict{String, String}, Int}}()

# CMRxRecon2024 ids are the in-archive path with the .mat extension stripped; the cached
# raw file restores it (joinpath turns the id's slashes into a directory tree).
_cache_basename(::CMRxRecon2024, e::DatasetEntry) = string(e.id, ".mat")

# Load (and memoise) the fragment entity-ID map + chunk size for one archive.
function _load_cmrxrecon_parts!(archive::AbstractString)
    haskey(_CMRXRECON_PARTS, archive) && return _CMRXRECON_PARTS[archive]
    spec = get(_ARCHIVES, archive, nothing)
    spec === nothing && error("unknown CMRxRecon2024 archive tag $(repr(archive))")
    isfile(spec.parts_path) || error(
        "missing Synapse entity-ID map $(spec.parts_path); generate it with " *
            "scripts/list_cmrxrecon2024_parts.jl (see scripts/README.md)",
    )
    raw = TOML.parsefile(spec.parts_path)
    parts = Dict{String, String}(String(k) => String(v) for (k, v) in get(raw, "parts", Dict{String, Any}()))
    chunk = Int(get(raw, "chunk_size", _DEFAULT_CHUNK_BYTES))
    _CMRXRECON_PARTS[archive] = (parts, chunk)
    return parts, chunk
end

# Synapse entity ID for fragment index `frag` (0-based) of one archive.
function _cmrxrecon_entity_id(spec::_ArchiveSpec, parts::Dict{String, String}, frag::Integer)
    name = spec.name_prefix * lpad(frag, spec.pad, '0')
    id = get(parts, name, nothing)
    id === nothing &&
        error("no Synapse entity ID known for fragment $name; regenerate $(spec.parts_path)")
    return id
end

# Resolve the temporary pre-signed S3 URL for a Synapse file entity. With
# `redirect=false`, Synapse returns the URL as the plain-text response body instead
# of issuing a 307 redirect, which lets us then range-request S3 directly without
# carrying the Synapse Authorization header onto the S3 leg.
function _synapse_presigned_url(entity_id::AbstractString, token::AbstractString)::String
    url = "$(_SYNAPSE_REPO)/entity/$(entity_id)/file?redirect=false"
    io = IOBuffer()
    Downloads.download(url, io; headers = ["Authorization" => "Bearer $(token)"])
    return strip(String(take!(io)))
end

# Total bytes a file occupies across the fragment span sf..ef. For a file inside a single
# fragment (ef == sf) the general expression collapses to `eo - so + 1`.
function _cmrxrecon_span_bytes(sf::Int, so::Int, ef::Int, eo::Int, chunk_size::Int)
    return (chunk_size - so) + (ef - sf - 1) * chunk_size + (eo + 1)
end

# Fetch raw bytes for a file spanning fragments sf..ef, stitching across boundaries.
# `update(n)` advances the caller's progress bar as bytes arrive.
function _fetch_fragment_bytes(
        spec::_ArchiveSpec, parts::Dict{String, String}, chunk_size::Int, token::AbstractString,
        sf::Int, so::Int, ef::Int, eo::Int, total::Int, update,
    )::Vector{UInt8}
    # The common case is a single fragment; returning its buffer directly avoids copying a
    # multi-hundred-MB member, so only the multi-fragment path stitches.
    url = _synapse_presigned_url(_cmrxrecon_entity_id(spec, parts, sf), token)
    if sf == ef
        return _download_range(url, so, eo; on_progress = (_rng_total, now) -> update(now))
    end

    buf = UInt8[]
    sizehint!(buf, total)
    done = Ref(0)
    for frag in sf:ef
        frag == sf || (url = _synapse_presigned_url(_cmrxrecon_entity_id(spec, parts, frag), token))
        rstart = frag == sf ? so : 0
        rend = frag == ef ? eo : chunk_size - 1
        chunk = _download_range(url, rstart, rend; on_progress = (_rng_total, now) -> update(done[] + Int(now)))
        append!(buf, chunk)
        done[] += length(chunk)
        update(done[])
    end
    return buf
end

function _fetch_dataset(::CMRxRecon2024, e::DatasetEntry, dest::AbstractString; progress::Bool, verify::Bool)
    archive = get(e.extra, "archive", "training")
    spec = get(_ARCHIVES, archive, nothing)
    spec === nothing && error("unknown CMRxRecon2024 archive tag $(repr(archive)) for $(e.id)")

    token = get_synapse_token()
    isempty(token) && error(
        "no Synapse token set; call MRITestData.set_synapse_token!(token) or set " *
            "ENV[\"SYNAPSE_AUTH_TOKEN\"]. Note the dataset also requires completing the " *
            "CMRxRecon2024 challenge registration before the token has download permission " *
            "(see the package README).",
    )
    parts, chunk_size = _load_cmrxrecon_parts!(archive)

    span = _zip_span(e)
    sf = Int(e.extra["start_frag"]::Integer)
    ef = Int(e.extra["end_frag"]::Integer)

    total = _cmrxrecon_span_bytes(sf, span.start_off, ef, span.end_off, chunk_size)
    bytes = _with_progress(total, _download_desc(e); progress = progress) do update
        _fetch_fragment_bytes(
            spec, parts, chunk_size, token,
            sf, span.start_off, ef, span.end_off, total, update,
        )
    end

    payload = _zip_member_payload(bytes, span.lfh_size, span.compression, e.id)
    return _finalize_download(e, dest, payload)
end
