#!/usr/bin/env julia
#
# Maintainer tool — generate a Synapse fragment entity-ID map for one CMRxRecon2024
# archive (data/cmrxrecon2024_parts.toml or data/cmrxrecon2024_aftercompetition_parts.toml).
#
# Lists the Synapse file entities that hold the archive's split fragments and writes a
# fragment-name → entity-ID map (plus the fragment chunk size) used by the runtime to
# resolve pre-signed S3 URLs for HTTP range requests.
#
# Both archives are handled identically; only the parent container, fragment-name
# prefix, and output path differ.
#
# Usage (training archive):
#   julia --project=. scripts/list_cmrxrecon2024_parts.jl <PARENT_SYNAPSE_ID>
#
# Usage (after-competition archive):
#   julia --project=. scripts/list_cmrxrecon2024_parts.jl <PARENT_SYNAPSE_ID> \
#       --prefix ChallengeData_AfterCompetition.zip-part- \
#       --out data/cmrxrecon2024_aftercompetition_parts.toml
#
# Options:
#   --prefix <str>       Fragment name prefix (default: "ChallengeData.zip-part-").
#   --out <path>         Output TOML path (default: data/cmrxrecon2024_parts.toml).
#   --chunk-size <n>     Standard fragment size in bytes (default: 4 GiB).
#   --token <PAT>        Synapse Personal Access Token. If omitted, falls back to
#                        $SYNAPSE_AUTH_TOKEN, then the stored synapse_token preference.
#
# <PARENT_SYNAPSE_ID> is the Synapse folder/container holding the fragment files.
# Requires outbound HTTPS to repo-prod.prod.sagebase.org.

include(joinpath(@__DIR__, "synapse_common.jl"))

function main(args)
    prefix = "ChallengeData.zip-part-"
    out = normpath(joinpath(@__DIR__, "..", "data", "cmrxrecon2024_parts.toml"))
    chunk_size = 4 * 1024^3
    token_arg = nothing
    positional = String[]
    i = 1
    while i <= length(args)
        if args[i] == "--prefix" && i < length(args)
            prefix = args[i + 1]; i += 2
        elseif args[i] == "--out" && i < length(args)
            out = args[i + 1]; i += 2
        elseif args[i] == "--chunk-size" && i < length(args)
            chunk_size = parse(Int, args[i + 1]); i += 2
        elseif args[i] == "--token" && i < length(args)
            token_arg = args[i + 1]; i += 2
        else
            push!(positional, args[i]); i += 1
        end
    end
    isempty(positional) && error(
        "usage: julia list_cmrxrecon2024_parts.jl <PARENT_SYNAPSE_ID> " *
            "[--prefix <str>] [--out <path>] [--chunk-size <n>] [--token <PAT>]",
    )
    parent = positional[1]
    token = resolve_synapse_token(token_arg)

    frags = list_fragments(parent, token, prefix)
    isempty(frags) && error("no $(prefix)* entities found under $parent")
    @info "found fragments" count = length(frags) prefix = prefix

    open(out, "w") do io
        println(io, "# Synapse entity IDs for the $(prefix)* fragments.")
        println(io, "# Generated by scripts/list_cmrxrecon2024_parts.jl from parent $(parent).")
        println(io)
        println(io, "chunk_size = ", chunk_size)
        println(io)
        println(io, "[parts]")
        for (name, id) in frags
            println(io, "\"", name, "\" = \"", id, "\"")
        end
    end
    return @info "wrote parts map" out fragments = length(frags)
end

abspath(PROGRAM_FILE) == abspath(@__FILE__) && main(ARGS)
