#!/usr/bin/env julia
#
# Phase 1b maintainer tool — generate data/cmrxrecon2024_parts.toml.
#
# Lists the Synapse file entities that hold the ChallengeData.zip fragments and
# writes a fragment-name → entity-ID map (plus the fragment chunk size) used by the
# runtime to resolve pre-signed S3 URLs.
#
# Usage:
#   julia scripts/list_cmrxrecon2024_parts.jl <SYNAPSE_PAT> <PARENT_SYNAPSE_ID> [chunk_size] [out.toml]
#
# <PARENT_SYNAPSE_ID> is the Synapse folder/container holding the
# ChallengeData.zip-part-NNN files (e.g. "syn12345678"). <chunk_size> defaults to
# 4 GiB (4294967296). Requires outbound HTTPS to repo-prod.prod.sagebase.org.

using Downloads

const SYNAPSE_REPO = "https://repo-prod.prod.sagebase.org/repo/v1"

# POST a JSON body and return the response as a String.
function synapse_post(path::AbstractString, body::AbstractString, token::AbstractString)
    out = IOBuffer()
    Downloads.request(
        SYNAPSE_REPO * path;
        method = "POST",
        input = IOBuffer(body),
        output = out,
        headers = [
            "Authorization" => "Bearer $(token)",
            "Content-Type" => "application/json",
            "Accept" => "application/json",
        ],
    )
    return String(take!(out))
end

# Extract (name, id) pairs from a Synapse `/entity/children` page response. Entity
# headers are flat JSON objects, so splitting the "page" array on object boundaries
# and pulling "id"/"name" from each is sufficient (no JSON dependency).
function extract_children(resp::AbstractString)
    pairs = Tuple{String, String}[]
    pstart = findfirst("\"page\":[", resp)
    pstart === nothing && return pairs, nothing
    # Take the page array body up to the matching closing bracket.
    rest = resp[(last(pstart) + 1):end]
    pend = findfirst(']', rest)
    page = pend === nothing ? rest : rest[1:(pend - 1)]
    for obj in split(page, "},{")
        idm = match(r"\"id\"\s*:\s*\"(syn\d+)\"", obj)
        nm = match(r"\"name\"\s*:\s*\"([^\"]+)\"", obj)
        (idm === nothing || nm === nothing) && continue
        push!(pairs, (String(nm.captures[1]), String(idm.captures[1])))
    end
    tokm = match(r"\"nextPageToken\"\s*:\s*\"([^\"]+)\"", resp)
    next = tokm === nothing ? nothing : String(tokm.captures[1])
    return pairs, next
end

function list_children(parent::AbstractString, token::AbstractString)
    parts = Dict{String, String}()
    next = nothing
    while true
        tokfield = next === nothing ? "" : ",\"nextPageToken\":\"$(next)\""
        body = "{\"parentId\":\"$(parent)\",\"includeTypes\":[\"file\"],\"sortBy\":\"NAME\"$(tokfield)}"
        resp = synapse_post("/entity/children", body, token)
        pairs, next = extract_children(resp)
        for (name, id) in pairs
            startswith(name, "ChallengeData.zip-part-") && (parts[name] = id)
        end
        next === nothing && break
    end
    return parts
end

function main(args)
    length(args) >= 2 || error("usage: julia list_cmrxrecon2024_parts.jl <SYNAPSE_PAT> <PARENT_SYNAPSE_ID> [chunk_size] [out.toml]")
    token = args[1]
    parent = args[2]
    chunk_size = length(args) >= 3 ? parse(Int, args[3]) : 4 * 1024^3
    out = length(args) >= 4 ? args[4] :
        normpath(joinpath(@__DIR__, "..", "data", "cmrxrecon2024_parts.toml"))

    parts = list_children(parent, token)
    isempty(parts) && error("no ChallengeData.zip-part-* entities found under $parent")
    @info "found fragments" count = length(parts)

    open(out, "w") do io
        println(io, "# Synapse entity IDs for the ChallengeData.zip fragments.")
        println(io, "# Generated by scripts/list_cmrxrecon2024_parts.jl.")
        println(io)
        println(io, "chunk_size = ", chunk_size)
        println(io)
        println(io, "[parts]")
        for name in sort(collect(keys(parts)))
            println(io, "\"", name, "\" = \"", parts[name], "\"")
        end
    end
    return @info "wrote parts map" out fragments = length(parts)
end

abspath(PROGRAM_FILE) == abspath(@__FILE__) && main(ARGS)
